# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tiago/Documents/Vespa/project_micro/project_micro.srcs/sources_1/bd/memory_ip/ip/memory_ip_MemBlock0_1/memory_ip_MemBlock0_1.xci
# IP: The module: 'memory_ip_MemBlock0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tiago/Documents/Vespa/project_micro/project_micro.gen/sources_1/bd/memory_ip/ip/memory_ip_MemBlock0_1/memory_ip_MemBlock0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory_ip_MemBlock0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/tiago/Documents/Vespa/project_micro/project_micro.srcs/sources_1/bd/memory_ip/ip/memory_ip_MemBlock0_1/memory_ip_MemBlock0_1.xci
# IP: The module: 'memory_ip_MemBlock0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tiago/Documents/Vespa/project_micro/project_micro.gen/sources_1/bd/memory_ip/ip/memory_ip_MemBlock0_1/memory_ip_MemBlock0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'memory_ip_MemBlock0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
