# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/top.xdc

# Block Designs: bd/memory_ip/memory_ip.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memory_ip || ORIG_REF_NAME==memory_ip} -quiet] -quiet

# IP: bd/memory_ip/ip/memory_ip_blk_mem_gen_0_1/memory_ip_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memory_ip_blk_mem_gen_0_1 || ORIG_REF_NAME==memory_ip_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/memory_ip/ip/memory_ip_MemBlock0_0/memory_ip_MemBlock0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memory_ip_MemBlock0_0 || ORIG_REF_NAME==memory_ip_MemBlock0_0} -quiet] -quiet

# IP: bd/memory_ip/ip/memory_ip_MemBlock0_1/memory_ip_MemBlock0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memory_ip_MemBlock0_1 || ORIG_REF_NAME==memory_ip_MemBlock0_1} -quiet] -quiet

# IP: bd/memory_ip/ip/memory_ip_MemBlock0_2/memory_ip_MemBlock0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==memory_ip_MemBlock0_2 || ORIG_REF_NAME==memory_ip_MemBlock0_2} -quiet] -quiet

# Block Designs: bd/RegFileIP/RegFileIP.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RegFileIP || ORIG_REF_NAME==RegFileIP} -quiet] -quiet

# IP: bd/RegFileIP/ip/RegFileIP_blk_mem_gen_0_0/RegFileIP_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RegFileIP_blk_mem_gen_0_0 || ORIG_REF_NAME==RegFileIP_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/RegFileIP/ip/RegFileIP_blk_mem_gen_0_1/RegFileIP_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RegFileIP_blk_mem_gen_0_1 || ORIG_REF_NAME==RegFileIP_blk_mem_gen_0_1} -quiet] -quiet

# XDC: /home/tiago/Documents/Vespa/project_micro/project_micro.gen/sources_1/bd/memory_ip/memory_ip_ooc.xdc

# XDC: /home/tiago/Documents/Vespa/project_micro/project_micro.gen/sources_1/bd/RegFileIP/RegFileIP_ooc.xdc
