# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/araujoj/Downloads/vespa25_11/project_micro_19-11_syntWorking/project_micro_13-11_loops/project_micro/project_micro.srcs/sources_1/bd/RegFileIP/ip/RegFileIP_blk_mem_gen_0_1/RegFileIP_blk_mem_gen_0_1.xci
# IP: The module: 'RegFileIP_blk_mem_gen_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/araujoj/Downloads/vespa25_11/project_micro_19-11_syntWorking/project_micro_13-11_loops/project_micro/project_micro.gen/sources_1/bd/RegFileIP/ip/RegFileIP_blk_mem_gen_0_1/RegFileIP_blk_mem_gen_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RegFileIP_blk_mem_gen_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/araujoj/Downloads/vespa25_11/project_micro_19-11_syntWorking/project_micro_13-11_loops/project_micro/project_micro.srcs/sources_1/bd/RegFileIP/ip/RegFileIP_blk_mem_gen_0_1/RegFileIP_blk_mem_gen_0_1.xci
# IP: The module: 'RegFileIP_blk_mem_gen_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/araujoj/Downloads/vespa25_11/project_micro_19-11_syntWorking/project_micro_13-11_loops/project_micro/project_micro.gen/sources_1/bd/RegFileIP/ip/RegFileIP_blk_mem_gen_0_1/RegFileIP_blk_mem_gen_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RegFileIP_blk_mem_gen_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
